### ISSUE TITLE
linux build from source, or debian12 binary

### ISSUE THREAD

**Issue by razholio** [Solaris17/ARC-Firmware-Tool#21]
Usually I prefer CLI, but this GUI looks to make the process much more convenient.  however, your preCompiled linux binary requires glibc-2.38, and debian12 shipped with glibc-2.36.  Maybe a flac or snap pkg would be easier, but a source build for linux would also work well.

**Comment by Solaris17** [comment]
Thanks. It does have a “manual mode” that exposes the cli for those that want it. As for the Linux libs I simply compiled them with what I had. I am toying with the idea of making a gui Linux version but if I did that would not be in this repo. As for snaps or rebuilding on an older version I simply don’t have the time; and am not sure I want to build for least common denominators. There is always someone running an LTS or an old version and that simply isn’t my vision at all at the moment.

**Comment by razholio** [comment]
Oh, I totally understand about not wanting to build binaries.  There are just too many targets.  Would it be possible to share your linux build so we could build our own?

**Comment by Solaris17** [comment]
Oh of course. It’s nothing special I simply built the raw IGSC repo using the cmake built steps.

https://github.com/intel/igsc

**Comment by razholio** [comment]
sorry, I meant a linux build for the ARC-FIrmware-Tool gui.  I see now that the 'Linux Build' subdir in that repo contains the linux binaries for igsc.  I just got confused.  Is there any chance of your windows GUI, ARC-Firmware-Tool, being built for linux?

**Comment by Solaris17** [comment]
Its a fleeting idea. I originally built the igsc source bins in the lnux folder so I can do cli testing. I played with the idea of using the qt framework since that will be less of a hill for me to climb if I were to port it.

The answer is maybe. If it was a yes, I would have no ETA. I have a few more features I want to add to this repo (the windows version) before I would even attempt a linux port.

I will keep what you said in mind though. While I have no interest in doing a snap or flatpak or multi target build, I will think about targeting debian main. I doubt anything runs an older glibc than it anyway.

**Comment by razholio** [comment]
totally understand.  I may have missed a good CLI only guide, but the --help  output is extremely brief.  I was hoping to find a guide on how to ID the correct firmware for my ASrock a380, download and flash with the CLI.  The GUI makes this look easy which is why I was trying to get that to work.

**Comment by cRaZy-bisCuiT** [comment]
@Solaris17 Thanks for the tool.

On question: The Linux build is pretty old. Is it still usable nowadays? I ordered a original Intel Arc A770 Limited Edition (16 GB) and want to try to cross flash it with a Flex 170 firmware.
