### ISSUE TITLE
Cant' flash

### ISSUE THREAD

**Issue by abc987** [Solaris17/ARC-Firmware-Tool#25]
When try to flash, it said no device found. It's weird because the gpu is actually detected but not the device?

"
ARC Firmware Tool Version: 1.30.0

Installed GPU driver version: 32.0.101.5768

Adapter Name: Intel(R) Arc(TM) A750 Graphics
GOP (vBIOS) Version: 20.0.1068

Listing Devices and FW/Oprom Versions:

No device found

Listing Devices HW Config:

Error: No device to check

Listing FW Data and FW Code Versions:

Error: No device or image

Listing OEM FW Version:

Error: No device to work with

Finished scanning hardware.
"

**Comment by Solaris17** [comment]
I cant reproduce this, though I dont have a A750. To much could be happening and there isnt enough info.

I would try to clean install the drivers to make certain the HECI driver is present/ correctly installed in device manager; from what I can see this reads as if there is a communication issue between the eeprom and the API.

I have seen this kind of communication issue happen when drivers are installed from an extracted package and not the installer itself.

Of course AV or a myriad of other issues can also block the HW access needed to perform the flash.

If you want to chase OS level blockers or configuration to make sure your system is in a proper state to flash that kind of technical help would be more appropriate here: https://www.techpowerup.com/forums/forums/intel-arc-gpus.94/

Otherwise, I would pull the latest driver and perform a clean install to re-attempt as mentioned above.
